typography_spectrum: 0.5184305889997631
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.17856123321689665
  lightness: 0.5496810078620911
  saturation: 0.5515904598869383
  rhythmicContrast: 0.3183064181357622
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.41288981889374554
analytics:
  google: null
  facebook: null
  twitter: null
name: One Drop Coffee
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Beans
    id: da3623f8-4b6a-42ef-9ccd-b2d09e90849b
    type: content
  - name: Cold Brew
    id: ca176ab6-17c5-47e5-b8da-266a189dfba4
    type: content
  - name: Location
    id: 8b617274-4ca0-4da6-b8c6-82102e40c9ae
    type: content
favicon: null
title: One Drop One Love Drink One Drop
purpose: []
