name: OneDropCoffee
favicon: null
layout_spectrum: 0.41288981889374554
typography_spectrum: 0.5184305889997631
style: the-composer
title: One Drop One Love Drink One Drop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.17856123321689665
  lightness: 0.5496810078620911
  saturation: 0.5515904598869383
  rhythmicContrast: 0.3183064181357622
purpose:
  - name: follow
    item: ea974062-015b-4f89-85f5-4814092fc7b9
    url: null
