name: OneDropCoffee
favicon: null
layout_spectrum: 0.22027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - name: follow
    item: ea974062-015b-4f89-85f5-4814092fc7b9
    url: null
